// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcMessageSerialization.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_grpcMessageSerialization_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_grpcMessageSerialization_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_grpcMessageSerialization_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_grpcMessageSerialization_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_grpcMessageSerialization_2eproto;
namespace grpcserver {
class setVariables;
class setVariablesDefaultTypeInternal;
extern setVariablesDefaultTypeInternal _setVariables_default_instance_;
class variablesSet;
class variablesSetDefaultTypeInternal;
extern variablesSetDefaultTypeInternal _variablesSet_default_instance_;
}  // namespace grpcserver
PROTOBUF_NAMESPACE_OPEN
template<> ::grpcserver::setVariables* Arena::CreateMaybeMessage<::grpcserver::setVariables>(Arena*);
template<> ::grpcserver::variablesSet* Arena::CreateMaybeMessage<::grpcserver::variablesSet>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace grpcserver {

// ===================================================================

class setVariables :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:grpcserver.setVariables) */ {
 public:
  setVariables();
  virtual ~setVariables();

  setVariables(const setVariables& from);
  setVariables(setVariables&& from) noexcept
    : setVariables() {
    *this = ::std::move(from);
  }

  inline setVariables& operator=(const setVariables& from) {
    CopyFrom(from);
    return *this;
  }
  inline setVariables& operator=(setVariables&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const setVariables& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const setVariables* internal_default_instance() {
    return reinterpret_cast<const setVariables*>(
               &_setVariables_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(setVariables& a, setVariables& b) {
    a.Swap(&b);
  }
  inline void Swap(setVariables* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline setVariables* New() const final {
    return CreateMaybeMessage<setVariables>(nullptr);
  }

  setVariables* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<setVariables>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const setVariables& from);
  void MergeFrom(const setVariables& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(setVariables* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "grpcserver.setVariables";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_grpcMessageSerialization_2eproto);
    return ::descriptor_table_grpcMessageSerialization_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeflectingvFieldNumber = 1,
    kAccelvFieldNumber = 2,
    kCurrentFieldNumber = 3,
    kMagneticarcFieldNumber = 4,
    kDeflectingpolarityFieldNumber = 5,
  };
  // int32 deflectingv = 1;
  void clear_deflectingv();
  ::PROTOBUF_NAMESPACE_ID::int32 deflectingv() const;
  void set_deflectingv(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_deflectingv() const;
  void _internal_set_deflectingv(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 accelv = 2;
  void clear_accelv();
  ::PROTOBUF_NAMESPACE_ID::int32 accelv() const;
  void set_accelv(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_accelv() const;
  void _internal_set_accelv(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 current = 3;
  void clear_current();
  ::PROTOBUF_NAMESPACE_ID::int32 current() const;
  void set_current(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_current() const;
  void _internal_set_current(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 magneticarc = 4;
  void clear_magneticarc();
  ::PROTOBUF_NAMESPACE_ID::int32 magneticarc() const;
  void set_magneticarc(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_magneticarc() const;
  void _internal_set_magneticarc(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 deflectingpolarity = 5;
  void clear_deflectingpolarity();
  ::PROTOBUF_NAMESPACE_ID::int32 deflectingpolarity() const;
  void set_deflectingpolarity(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_deflectingpolarity() const;
  void _internal_set_deflectingpolarity(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:grpcserver.setVariables)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 deflectingv_;
  ::PROTOBUF_NAMESPACE_ID::int32 accelv_;
  ::PROTOBUF_NAMESPACE_ID::int32 current_;
  ::PROTOBUF_NAMESPACE_ID::int32 magneticarc_;
  ::PROTOBUF_NAMESPACE_ID::int32 deflectingpolarity_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_grpcMessageSerialization_2eproto;
};
// -------------------------------------------------------------------

class variablesSet :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:grpcserver.variablesSet) */ {
 public:
  variablesSet();
  virtual ~variablesSet();

  variablesSet(const variablesSet& from);
  variablesSet(variablesSet&& from) noexcept
    : variablesSet() {
    *this = ::std::move(from);
  }

  inline variablesSet& operator=(const variablesSet& from) {
    CopyFrom(from);
    return *this;
  }
  inline variablesSet& operator=(variablesSet&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const variablesSet& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const variablesSet* internal_default_instance() {
    return reinterpret_cast<const variablesSet*>(
               &_variablesSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(variablesSet& a, variablesSet& b) {
    a.Swap(&b);
  }
  inline void Swap(variablesSet* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline variablesSet* New() const final {
    return CreateMaybeMessage<variablesSet>(nullptr);
  }

  variablesSet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<variablesSet>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const variablesSet& from);
  void MergeFrom(const variablesSet& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(variablesSet* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "grpcserver.variablesSet";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_grpcMessageSerialization_2eproto);
    return ::descriptor_table_grpcMessageSerialization_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFlagFieldNumber = 1,
  };
  // bool flag = 1;
  void clear_flag();
  bool flag() const;
  void set_flag(bool value);
  private:
  bool _internal_flag() const;
  void _internal_set_flag(bool value);
  public:

  // @@protoc_insertion_point(class_scope:grpcserver.variablesSet)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  bool flag_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_grpcMessageSerialization_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// setVariables

// int32 deflectingv = 1;
inline void setVariables::clear_deflectingv() {
  deflectingv_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 setVariables::_internal_deflectingv() const {
  return deflectingv_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 setVariables::deflectingv() const {
  // @@protoc_insertion_point(field_get:grpcserver.setVariables.deflectingv)
  return _internal_deflectingv();
}
inline void setVariables::_internal_set_deflectingv(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  deflectingv_ = value;
}
inline void setVariables::set_deflectingv(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_deflectingv(value);
  // @@protoc_insertion_point(field_set:grpcserver.setVariables.deflectingv)
}

// int32 accelv = 2;
inline void setVariables::clear_accelv() {
  accelv_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 setVariables::_internal_accelv() const {
  return accelv_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 setVariables::accelv() const {
  // @@protoc_insertion_point(field_get:grpcserver.setVariables.accelv)
  return _internal_accelv();
}
inline void setVariables::_internal_set_accelv(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  accelv_ = value;
}
inline void setVariables::set_accelv(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_accelv(value);
  // @@protoc_insertion_point(field_set:grpcserver.setVariables.accelv)
}

// int32 current = 3;
inline void setVariables::clear_current() {
  current_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 setVariables::_internal_current() const {
  return current_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 setVariables::current() const {
  // @@protoc_insertion_point(field_get:grpcserver.setVariables.current)
  return _internal_current();
}
inline void setVariables::_internal_set_current(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  current_ = value;
}
inline void setVariables::set_current(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_current(value);
  // @@protoc_insertion_point(field_set:grpcserver.setVariables.current)
}

// int32 magneticarc = 4;
inline void setVariables::clear_magneticarc() {
  magneticarc_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 setVariables::_internal_magneticarc() const {
  return magneticarc_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 setVariables::magneticarc() const {
  // @@protoc_insertion_point(field_get:grpcserver.setVariables.magneticarc)
  return _internal_magneticarc();
}
inline void setVariables::_internal_set_magneticarc(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  magneticarc_ = value;
}
inline void setVariables::set_magneticarc(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_magneticarc(value);
  // @@protoc_insertion_point(field_set:grpcserver.setVariables.magneticarc)
}

// int32 deflectingpolarity = 5;
inline void setVariables::clear_deflectingpolarity() {
  deflectingpolarity_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 setVariables::_internal_deflectingpolarity() const {
  return deflectingpolarity_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 setVariables::deflectingpolarity() const {
  // @@protoc_insertion_point(field_get:grpcserver.setVariables.deflectingpolarity)
  return _internal_deflectingpolarity();
}
inline void setVariables::_internal_set_deflectingpolarity(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  deflectingpolarity_ = value;
}
inline void setVariables::set_deflectingpolarity(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_deflectingpolarity(value);
  // @@protoc_insertion_point(field_set:grpcserver.setVariables.deflectingpolarity)
}

// -------------------------------------------------------------------

// variablesSet

// bool flag = 1;
inline void variablesSet::clear_flag() {
  flag_ = false;
}
inline bool variablesSet::_internal_flag() const {
  return flag_;
}
inline bool variablesSet::flag() const {
  // @@protoc_insertion_point(field_get:grpcserver.variablesSet.flag)
  return _internal_flag();
}
inline void variablesSet::_internal_set_flag(bool value) {
  
  flag_ = value;
}
inline void variablesSet::set_flag(bool value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:grpcserver.variablesSet.flag)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace grpcserver

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_grpcMessageSerialization_2eproto
