// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpcMessageSerialization.proto

#include "grpcMessageSerialization.pb.h"
#include "grpcMessageSerialization.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace grpcserver {

static const char* messagePassing_method_names[] = {
  "/grpcserver.messagePassing/sendVariables",
};

std::unique_ptr< messagePassing::Stub> messagePassing::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< messagePassing::Stub> stub(new messagePassing::Stub(channel));
  return stub;
}

messagePassing::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_sendVariables_(messagePassing_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status messagePassing::Stub::sendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpcserver::variablesSet* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_sendVariables_, context, request, response);
}

void messagePassing::Stub::experimental_async::sendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendVariables_, context, request, response, std::move(f));
}

void messagePassing::Stub::experimental_async::sendVariables(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::grpcserver::variablesSet* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendVariables_, context, request, response, std::move(f));
}

void messagePassing::Stub::experimental_async::sendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_sendVariables_, context, request, response, reactor);
}

void messagePassing::Stub::experimental_async::sendVariables(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::grpcserver::variablesSet* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_sendVariables_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grpcserver::variablesSet>* messagePassing::Stub::AsyncsendVariablesRaw(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::grpcserver::variablesSet>::Create(channel_.get(), cq, rpcmethod_sendVariables_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::grpcserver::variablesSet>* messagePassing::Stub::PrepareAsyncsendVariablesRaw(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::grpcserver::variablesSet>::Create(channel_.get(), cq, rpcmethod_sendVariables_, context, request, false);
}

messagePassing::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      messagePassing_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< messagePassing::Service, ::grpcserver::setVariables, ::grpcserver::variablesSet>(
          std::mem_fn(&messagePassing::Service::sendVariables), this)));
}

messagePassing::Service::~Service() {
}

::grpc::Status messagePassing::Service::sendVariables(::grpc::ServerContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpcserver

