// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpcMessageSerialization.proto
#ifndef GRPC_grpcMessageSerialization_2eproto__INCLUDED
#define GRPC_grpcMessageSerialization_2eproto__INCLUDED

#include "grpcMessageSerialization.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace grpcserver {

// The message passing serialization service definition.
class messagePassing final {
 public:
  static constexpr char const* service_full_name() {
    return "grpcserver.messagePassing";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a message containing variables in struct and returns bool of success
    virtual ::grpc::Status sendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpcserver::variablesSet* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcserver::variablesSet>> AsyncsendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcserver::variablesSet>>(AsyncsendVariablesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcserver::variablesSet>> PrepareAsyncsendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpcserver::variablesSet>>(PrepareAsyncsendVariablesRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a message containing variables in struct and returns bool of success
      virtual void sendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response, std::function<void(::grpc::Status)>) = 0;
      virtual void sendVariables(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::grpcserver::variablesSet* response, std::function<void(::grpc::Status)>) = 0;
      virtual void sendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void sendVariables(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::grpcserver::variablesSet* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcserver::variablesSet>* AsyncsendVariablesRaw(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpcserver::variablesSet>* PrepareAsyncsendVariablesRaw(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status sendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpcserver::variablesSet* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcserver::variablesSet>> AsyncsendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcserver::variablesSet>>(AsyncsendVariablesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcserver::variablesSet>> PrepareAsyncsendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpcserver::variablesSet>>(PrepareAsyncsendVariablesRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void sendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response, std::function<void(::grpc::Status)>) override;
      void sendVariables(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::grpcserver::variablesSet* response, std::function<void(::grpc::Status)>) override;
      void sendVariables(::grpc::ClientContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void sendVariables(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::grpcserver::variablesSet* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpcserver::variablesSet>* AsyncsendVariablesRaw(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpcserver::variablesSet>* PrepareAsyncsendVariablesRaw(::grpc::ClientContext* context, const ::grpcserver::setVariables& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_sendVariables_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a message containing variables in struct and returns bool of success
    virtual ::grpc::Status sendVariables(::grpc::ServerContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_sendVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_sendVariables() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_sendVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendVariables(::grpc::ServerContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendVariables(::grpc::ServerContext* context, ::grpcserver::setVariables* request, ::grpc::ServerAsyncResponseWriter< ::grpcserver::variablesSet>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_sendVariables<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_sendVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_sendVariables() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpcserver::setVariables, ::grpcserver::variablesSet>(
          [this](::grpc::ServerContext* context,
                 const ::grpcserver::setVariables* request,
                 ::grpcserver::variablesSet* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->sendVariables(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_sendVariables(
        ::grpc::experimental::MessageAllocator< ::grpcserver::setVariables, ::grpcserver::variablesSet>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::grpcserver::setVariables, ::grpcserver::variablesSet>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_sendVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendVariables(::grpc::ServerContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void sendVariables(::grpc::ServerContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_sendVariables<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_sendVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_sendVariables() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_sendVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendVariables(::grpc::ServerContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_sendVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_sendVariables() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_sendVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendVariables(::grpc::ServerContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendVariables(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_sendVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_sendVariables() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->sendVariables(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_sendVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendVariables(::grpc::ServerContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void sendVariables(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_sendVariables : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_sendVariables() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::grpcserver::setVariables, ::grpcserver::variablesSet>(std::bind(&WithStreamedUnaryMethod_sendVariables<BaseClass>::StreamedsendVariables, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_sendVariables() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status sendVariables(::grpc::ServerContext* context, const ::grpcserver::setVariables* request, ::grpcserver::variablesSet* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsendVariables(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpcserver::setVariables,::grpcserver::variablesSet>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_sendVariables<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_sendVariables<Service > StreamedService;
};

}  // namespace grpcserver


#endif  // GRPC_grpcMessageSerialization_2eproto__INCLUDED
